DOCKER_IMAGE_NAME := feedback3
DOCKER_CONTAINER_NAME := $(DOCKER_IMAGE_NAME)--vm

FILEPATH :=

build:
	cd docker && sudo docker-compose build

up:
	cd docker && sudo docker-compose up

exec:
	cd docker && sudo docker-compose exec dev bash
