name: cat_weighted

params:
  task_type: GPU
  loss_function: RMSE
  learning_rate: 0.1
  iterations: 2000
  bagging_temperature: 0.5
  max_depth: 12
  l2_leaf_reg: 1.25
  min_data_in_leaf: 24
  random_strength: 0.25
  use_best_model: True
